apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: ${namespace}
data:
  realm.json: |
    {
      "realm": "${realm_name}",
      "enabled": true,
      "clients": [
        {
          "clientId": "${client_id}",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "${client_secret}",
          "directAccessGrantsEnabled": true
        }
      ]
    }
