resources:
  - search_gateway_deployment.yaml
  - search_gateway_service.yaml

configMapGenerator:
  - name: search-gateway-trigger
    files:
      - version.txt

generatorOptions:
  disableNameSuffixHash: false