apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-gateway-deployment
  namespace: smart-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-gateway
  template:
    metadata:
      labels:
        app: search-gateway
      annotations:
        version: '4'
    spec:
      containers:
      - name: search-gateway
        image: dansil2301/search_gateway:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: SECRET
          value: CRAZY_HAMBURGER
        - name: MONGO_URI
          value: mongodb+srv://dansil2301:Varvara88@smartsearchusers.bnqnzwz.mongodb.net/?retryWrites=true&w=majority&appName=SmartSearchUsers
        - name: LLM_URL
          value: http://search-llm-service:80
        - name: SEARCH_URL
          value: http://search-engine-service:80
